### ISSUE TITLE
Limit Indicators

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/Quad#10]
I find that I sometimes lose in the following situation:

A 'floating' pair of blocks is far away from the center of the board (lets say, on the right) and I want to clear the pair by dropping a quad onto it. However, in order to drop the quad on the pair, I need to move the contents of the board to the left (so the pair is under the center). It is difficult to see, though, whether I will be able to move far enough left, or If I will hit the left wall with some block. If it turns out I can't reach the floating pair, I run out of time, the waiting quad drops, and I lose.

I think we need an indicator of the maximum distance the player could possibly drop a quad, probably as some subtle marker.

**Comment by willharrison** [comment]
I've also had that issue.  Maybe we could slightly darken the areas (the sides) where it is impossible to drop, depending on the side of the grid you have the quad on.  If that makes sense.

**Comment by ALSchwalm** [comment]
I like that a lot. I'm going to go ahead and assign this to me and start working on it.
