### ISSUE TITLE
Gameover and Pause screen are too large

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/Quad#28]
Both game over and the pause screen cause a scroll bar to appear. See example below.

![2015-02-01-184534_893x604_scrot](https://cloud.githubusercontent.com/assets/1063999/5994686/97115d4a-aa42-11e4-9419-27022f1d6c7c.png)

**Comment by willharrison** [comment]
also having this issue

**Comment by willharrison** [comment]
assign this to me.

**Comment by ALSchwalm** [comment]
Fixed by fb95c1dfbad408
