### ISSUE TITLE
computer gets hot after leaving game open for a little while.

### ISSUE THREAD

**Issue by willharrison** [ALSchwalm/Quad#3]
my computer's cpu got up to 79c while leaving the game open.  probably need to look into that.

**Comment by ALSchwalm** [comment]
What OS/browser are you using?

**Comment by willharrison** [comment]
osx 1.10 and chrome 39.

**Comment by ALSchwalm** [comment]
Can you post the contents of the chrome console? It should list of the Phaser and Pixi.js versions, etc.

**Comment by willharrison** [comment]
`Phaser v2.2.1 | Pixi.js v2.2.0 | WebGL | WebAudio     http://phaser.io ♥♥♥`

**Comment by ALSchwalm** [comment]
Is there any effect if you change Phaser.AUTO to Phaser.CANVAS in game.js?

**Comment by willharrison** [comment]
It still starts getting hot.  Putting it on WEBGL doesn't help either (didn't know which one AUTO would default to).  Seems to happen mainly on Chrome.  Safari is handling it much better (still up there a little).  I have an update for Safari due too, so I will see how it performs after I update.

**Comment by willharrison** [comment]
issue with chrome
